services:
  postgres:
    image: postgres:17
    container_name: reonic-postgres
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    ports:
      - "${PGPORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  lambda:
    build:
      context: ./app
      dockerfile: Dockerfile.local
    container_name: reonic-lambda
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${PGDATABASE}
      DB_USER: ${PGUSER}
      DB_PASSWORD: ${PGPASSWORD}
    ports:
      - "9000:8080"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./app/node_modules:/app/node_modules:ro
