name: Deploy CDK Stack

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          npm install -g aws-cdk
          npm run install:all

      - name: Build application
        run: npm run build:app

# Add your code to deploy the App here
